# fly.toml app configuration file generated for notification-backend on 2024-01-15T10:00:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "notification-backend"
primary_region = "iad"

[build]

[env]
  PORT = "8080"
  NODE_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/api/health"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 512

[mounts]
  source = "notification_data"
  destination = "/app/uploads" 